/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Data;
import javax.swing.JOptionPane;
import Controller.Vendedor;
import java.awt.Color;
import java.awt.Font;
import java.io.*;

/**
 *
 * @author sarah
 */
public class JFormCadastroVendedor extends javax.swing.JFrame {

    /**
     * Creates new form JFormCadastroVendedor
     */
    public JFormCadastroVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_rg = new javax.swing.JTextField();
        txt_nasc = new javax.swing.JTextField();
        txt_adm = new javax.swing.JTextField();
        txt_sal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_tempo = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_busca = new javax.swing.JTextField();
        btn_buscar1 = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_senha = new javax.swing.JTextField();
        txt_gerente = new javax.swing.JTextField();
        btn_buscar2 = new javax.swing.JButton();

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Cadastro - VENDEDOR");

        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText(" Nome");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField3.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField3.setName("txt_nome"); // NOI18N

        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText(" RG");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField4.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField4.setName("txt_marca"); // NOI18N

        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText(" Gerente responsável");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField8.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField8.setName("txt_gerente"); // NOI18N

        jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        jTextField11.setText(" Data de nascimento: __/__/____");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField11.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField11.setName("txt_nasc"); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField17.setForeground(new java.awt.Color(153, 153, 153));
        jTextField17.setText(" Data de admissão: __/__/____");
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField17.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField17.setName("txt_admi"); // NOI18N

        jTextField34.setForeground(new java.awt.Color(153, 153, 153));
        jTextField34.setText(" Salário");
        jTextField34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField34.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField34.setName("txt_sal"); // NOI18N
        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        jTextField36.setForeground(new java.awt.Color(153, 153, 153));
        jTextField36.setText(" Tempo de treinamento restante");
        jTextField36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField36.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField36.setName("txt_tempo"); // NOI18N
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.setName("btn_cadastrar"); // NOI18N

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Cancelar");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jButton5.setName("btn_cancelar"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3)
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar.setEnabled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("VENDEDOR");

        txt_nome.setForeground(new java.awt.Color(153, 153, 153));
        txt_nome.setText(" Nome");
        txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_nome.setEnabled(false);
        txt_nome.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_nome.setName("txt_nome"); // NOI18N
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomeFocusGained(evt);
            }
        });

        txt_rg.setForeground(new java.awt.Color(153, 153, 153));
        txt_rg.setText(" RG");
        txt_rg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_rg.setEnabled(false);
        txt_rg.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_rg.setName("txt_rg"); // NOI18N
        txt_rg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rgFocusGained(evt);
            }
        });

        txt_nasc.setForeground(new java.awt.Color(153, 153, 153));
        txt_nasc.setText(" Data de nascimento: __/__/____");
        txt_nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_nasc.setEnabled(false);
        txt_nasc.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_nasc.setName("txt_nasc"); // NOI18N
        txt_nasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nascFocusGained(evt);
            }
        });
        txt_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nascActionPerformed(evt);
            }
        });

        txt_adm.setForeground(new java.awt.Color(153, 153, 153));
        txt_adm.setText(" Data de admissão: __/__/____");
        txt_adm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_adm.setEnabled(false);
        txt_adm.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_adm.setName("txt_admi"); // NOI18N
        txt_adm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_admFocusGained(evt);
            }
        });

        txt_sal.setForeground(new java.awt.Color(153, 153, 153));
        txt_sal.setText(" Salário");
        txt_sal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_sal.setEnabled(false);
        txt_sal.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_sal.setName("txt_sal"); // NOI18N
        txt_sal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_salFocusGained(evt);
            }
        });
        txt_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        txt_tempo.setForeground(new java.awt.Color(153, 153, 153));
        txt_tempo.setText(" Tempo de treinamento restante");
        txt_tempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_tempo.setEnabled(false);
        txt_tempo.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_tempo.setName("txt_tempo"); // NOI18N
        txt_tempo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tempoFocusGained(evt);
            }
        });
        txt_tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tempoActionPerformed(evt);
            }
        });

        btn_cadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setName("btn_cadastrar"); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(0, 102, 102));
        btn_alterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(255, 255, 255));
        btn_alterar.setText("Alterar");
        btn_alterar.setName("btn_cadastrar"); // NOI18N
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(0, 102, 102));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.setName("btn_cadastrar"); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(0, 102, 102));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Confirmar");
        btn_salvar.setEnabled(false);
        btn_salvar.setName("btn_salvar"); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 102, 102));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_cancelar.setName("btn_cancelar"); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txt_busca.setForeground(new java.awt.Color(153, 153, 153));
        txt_busca.setText(" Buscar pelo número do RG");
        txt_busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_busca.setEnabled(false);
        txt_busca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_busca.setName("txt_busca"); // NOI18N
        txt_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscaFocusGained(evt);
            }
        });

        btn_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar1.setEnabled(false);
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        txt_email.setForeground(new java.awt.Color(153, 153, 153));
        txt_email.setText(" Email");
        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_email.setEnabled(false);
        txt_email.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_email.setName("txt_nome"); // NOI18N
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
        });

        txt_senha.setForeground(new java.awt.Color(153, 153, 153));
        txt_senha.setText(" Senha");
        txt_senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_senha.setEnabled(false);
        txt_senha.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_senha.setName("txt_cpf"); // NOI18N
        txt_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_senhaFocusGained(evt);
            }
        });

        txt_gerente.setForeground(new java.awt.Color(153, 153, 153));
        txt_gerente.setText(" Buscar pelo RG do gerente");
        txt_gerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_gerente.setEnabled(false);
        txt_gerente.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_gerente.setName("txt_busca"); // NOI18N
        txt_gerente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_gerenteFocusGained(evt);
            }
        });
        txt_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gerenteActionPerformed(evt);
            }
        });

        btn_buscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar2.setEnabled(false);
        btn_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_tempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(txt_rg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txt_sal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(btn_cadastrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_alterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_excluir)
                                        .addGap(51, 51, 51)
                                        .addComponent(btn_salvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(15, 15, 15))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nascActionPerformed

    private void txt_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salActionPerformed

    private void txt_tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tempoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        txt_nome.setEnabled(true);
        txt_rg.setEnabled(true);
        txt_tempo.setEnabled(true);
        txt_nasc.setEnabled(true);
        txt_adm.setEnabled(true);
        txt_sal.setEnabled(true);
        txt_gerente.setEnabled(true);
        btn_buscar2.setEnabled(true);
        txt_email.setEnabled(true);
        txt_senha.setEnabled(true);
        
        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar1.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar1.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_salvar.setEnabled(true);

    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        JFormCadastroVendedor.this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        //Verificar se achou o número, se achou fazer tudo aqui embaixo
        String rgV;
        boolean flag = false;
        
        txt_nome.setText("");
        txt_rg.setText("");
        txt_tempo.setText("");
        txt_nasc.setText("");
        txt_adm.setText("");
        txt_sal.setText("");
        txt_email.setText("");
        txt_senha.setText("");
        txt_gerente.setText("");
        
        btn_buscar2.setEnabled(false);
        btn_salvar.setEnabled(true);
        txt_busca.setEnabled(false);
        btn_buscar2.setEnabled(false);

        rgV = txt_busca.getText();
        if(rgV.isEmpty() || rgV.equals("Buscar pelo número do RG"))
        {
            JOptionPane.showMessageDialog(null, "Insira o número do rg!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            try
            {
                FileReader arq = new FileReader(".//src//Model//vendedores.txt");
                BufferedReader lerArq = new BufferedReader(arq);
                while(lerArq.ready() && flag == false)
                {
                    String linha = lerArq.readLine();
                    String[] dadoSeparado = linha.split(";");
                    if(dadoSeparado[0].equals(rgV))
                    {
                        flag = true;
                        
                        txt_rg.setText(rgV);
                        txt_nome.setText(dadoSeparado[1]);
                        txt_tempo.setText(dadoSeparado[7]);
                        txt_email.setText(dadoSeparado[5]);
                        txt_senha.setText(dadoSeparado[6]);
                        txt_nasc.setText(dadoSeparado[2]);
                        txt_adm.setText(dadoSeparado[3]);
                        txt_sal.setText(dadoSeparado[4]);
                        txt_gerente.setText(dadoSeparado[8]);
                    }
                }

                lerArq.close();
                if(flag == false)
                     JOptionPane.showMessageDialog(null, "RG não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados no arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
                
            }

        }

        if(this.btn_alterar.isEnabled())
        {
            txt_nome.setEnabled(true);
            txt_rg.setEnabled(true);
            txt_tempo.setEnabled(true);
            txt_nasc.setEnabled(true);
            txt_adm.setEnabled(true);
            txt_sal.setEnabled(true);
            txt_gerente.setEnabled(true);
            btn_buscar2.setEnabled(true);
            txt_email.setEnabled(true);
            txt_senha.setEnabled(true);
        }

        else if(this.btn_excluir.isEnabled())
        {
            txt_nome.setEnabled(false);
            txt_rg.setEnabled(false);
            txt_tempo.setEnabled(false);
            txt_nasc.setEnabled(false);
            txt_adm.setEnabled(false);
            txt_sal.setEnabled(false);
            txt_gerente.setEnabled(false);
            btn_buscar2.setEnabled(false);
            txt_email.setEnabled(false);
            txt_senha.setEnabled(false);
        }
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
      if((this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false) || (btn_cadastrar.isEnabled() == false && btn_excluir.isEnabled() == false))
        {
           String rg, nome, email, senha,data_nasc, data_adm, gerente;
           int tempo;
           double salario;
            
           //Pega os dados
           rg = txt_rg.getText();
           nome = txt_nome.getText();
           email = txt_email.getText();
           gerente = txt_gerente.getText();
           senha = txt_senha.getText();
           data_nasc = txt_nasc.getText();
           data_adm = txt_adm.getText();
           tempo = Integer.parseInt(txt_tempo.getText());
           salario = Double.parseDouble(txt_sal.getText());
           
           //Confere
           if(rg.isEmpty() || rg.equals("RG"))
                  JOptionPane.showMessageDialog(null, "Campo RG não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(nome.isEmpty() || nome.equals("Nome"))
                  JOptionPane.showMessageDialog(null, "Campo nome não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(gerente.isEmpty() || gerente.equals("Nome"))
                  JOptionPane.showMessageDialog(null, "Campo gerente não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            
            else if(email.isEmpty() || email.equals("Email") || email.contains("@") == false)
                JOptionPane.showMessageDialog(null, "Campo email não preenchido ou inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(senha.isEmpty() || senha.equals("Senha"))
                JOptionPane.showMessageDialog(null, "Campo senha não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(salario < 0)
                JOptionPane.showMessageDialog(null, "Salário inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(tempo < 0)
                JOptionPane.showMessageDialog(null, "empo de treinamento. inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(data_nasc.isEmpty() || data_nasc.equals("Data de nascimento: __/__/____"))
                JOptionPane.showMessageDialog(null, "Campo data de nascimento não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(data_adm.isEmpty() || data_adm.equals("Data de admissão: __/__/____"))
                JOptionPane.showMessageDialog(null, "Campo data de admissão não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            else
           {
               //Cria objeto - DATA???????
               Data data = new Data();
               Data data1 = new Data();
               data.setData(data_nasc);
               data1.setData(data_adm);
               Vendedor vendedor = new Vendedor(rg, nome, data, data1, salario,email, senha, tempo, gerente);
               if(this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false)
               {
                   vendedor.cadastrar(); //Cadastrar
                   JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                   //JFormCadastroMoto.this.setVisible(false);
               }
                    
               
               else //Alterar
               {
                   vendedor.alterar();
                   JOptionPane.showMessageDialog(null, "Vendedor alterado com sucesso!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                   //JFormCadastroMoto.this.setVisible(false);
               }
           }
        }
        
        else if(btn_cadastrar.isEnabled() == false && btn_alterar.isEnabled() == false) //Excluir
        {
            Vendedor vendedor = new Vendedor(txt_rg.getText());
            vendedor.excluir();
            JOptionPane.showMessageDialog(null, "Vendedor excluído com sucesso!", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
            //JFormCadastroMoto.this.setVisible(false);
        }
        
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_salvar.setEnabled(false);
        
       //Limpa os campos
       Font fonte = new Font("Tahoma", Font.PLAIN, 11);
       
       txt_nome.setFont(fonte);
       txt_nome.setForeground(Color.LIGHT_GRAY);
       txt_rg.setFont(fonte);
       txt_rg.setForeground(Color.LIGHT_GRAY);
       txt_tempo.setFont(fonte);
       txt_tempo.setForeground(Color.LIGHT_GRAY);
       txt_email.setFont(fonte);
       txt_email.setForeground(Color.LIGHT_GRAY);
       txt_senha.setFont(fonte);
       txt_senha.setForeground(Color.LIGHT_GRAY);
       txt_nasc.setFont(fonte);
       txt_nasc.setForeground(Color.LIGHT_GRAY);
       txt_adm.setFont(fonte);
       txt_adm.setForeground(Color.LIGHT_GRAY);
       txt_sal.setFont(fonte);
       txt_sal.setForeground(Color.LIGHT_GRAY);
       txt_busca.setFont(fonte);
       txt_busca.setForeground(Color.LIGHT_GRAY);
       txt_gerente.setFont(fonte);
       txt_gerente.setForeground(Color.LIGHT_GRAY);
       
       txt_nome.setText("Nme");
       txt_rg.setText("RG");
       txt_tempo.setText("Tempo de treinamento restante");
       txt_email.setText("Email");
       txt_senha.setText("Senha");
       txt_nasc.setText("Data de nascimento: __/__/____ ");
       txt_adm.setText("Data de dmissão: __/__/____");
       txt_sal.setText("alário");
       txt_busca.setText("Buscar pelo número do RG");
       txt_gerente.setText("Buscar pelo RG do gerente");
       
       txt_nome.setEnabled(false);
       txt_rg.setEnabled(false);
       txt_tempo.setEnabled(false);
       txt_email.setEnabled(false);
       txt_senha.setEnabled(false);
       txt_nasc.setEnabled(false);
       txt_adm.setEnabled(false);
       txt_sal.setEnabled(false);
       txt_busca.setEnabled(false);
       txt_gerente.setEnabled(false);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar2ActionPerformed
       String rgG;
       boolean flag = false;
        
        rgG = txt_gerente.getText();
        if(rgG.isEmpty() || rgG.equals(" Busca pelo RG do gerente"))
        {
            JOptionPane.showMessageDialog(null, "Insira o RG do gerente!", "Erro", JOptionPane.ERROR_MESSAGE);
            txt_gerente.setText("");
        }
        
        else
        {
            try
            {
                FileReader arq = new FileReader(".//src//Model//gerente.txt");
                BufferedReader lerArq = new BufferedReader(arq);
                while(lerArq.ready() && flag == false)
                {
                    String linha = lerArq.readLine();
                    String[] dadoSeparado = linha.split(";");
                    if(dadoSeparado[0].equals(rgG))
                    {
                        flag = true;

                        txt_gerente.setText(rgG);
;
                    }
                    
                    JOptionPane.showMessageDialog(null, "Gerente encontrado com sucesso!", "Gerente", JOptionPane.INFORMATION_MESSAGE);

                }

                lerArq.close();
                if(flag == false)
                {
                    JOptionPane.showMessageDialog(null, "RG não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                    txt_gerente.setText("");
                }
                

            }

            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados no arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
                txt_gerente.setText("");
            }
        }
    }//GEN-LAST:event_btn_buscar2ActionPerformed

    private void txt_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusGained
       txt_nome.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_nome.setFont(fonte);
        txt_nome.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_nomeFocusGained

    private void txt_rgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rgFocusGained
        txt_rg.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_rg.setFont(fonte);
        txt_rg.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_rgFocusGained

    private void txt_tempoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tempoFocusGained
        txt_tempo.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_tempo.setFont(fonte);
        txt_tempo.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_tempoFocusGained

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
       txt_email.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_email.setFont(fonte);
        txt_email.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_senhaFocusGained
       txt_senha.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_senha.setFont(fonte);
        txt_senha.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_senhaFocusGained

    private void txt_nascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nascFocusGained
        txt_nasc.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_nasc.setFont(fonte);
        txt_nasc.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_nascFocusGained

    private void txt_admFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_admFocusGained
       txt_adm.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_adm.setFont(fonte);
        txt_adm.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_admFocusGained

    private void txt_salFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_salFocusGained
        txt_sal.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_sal.setFont(fonte);
        txt_sal.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_salFocusGained

    private void txt_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gerenteActionPerformed

    private void txt_gerenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_gerenteFocusGained
      txt_gerente.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_gerente.setFont(fonte);
        txt_gerente.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_gerenteFocusGained

    private void txt_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscaFocusGained
      txt_busca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_buscaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCadastroVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_buscar2;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txt_adm;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_gerente;
    private javax.swing.JTextField txt_nasc;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_sal;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_tempo;
    // End of variables declaration//GEN-END:variables
}
