/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Data;
import Controller.Gerente;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author sarah
 */
public class JFormCadastroGerente extends javax.swing.JFrame {

    /**
     * Creates new form JFormCadastroGerente
     */
    public JFormCadastroGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField35 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_rg = new javax.swing.JTextField();
        txt_nasc = new javax.swing.JTextField();
        txt_adm = new javax.swing.JTextField();
        txt_sal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_anos = new javax.swing.JTextField();
        txt_busca = new javax.swing.JTextField();
        btn_buscar1 = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_senha = new javax.swing.JTextField();

        jTextField35.setForeground(new java.awt.Color(153, 153, 153));
        jTextField35.setText(" Salário");
        jTextField35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField35.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField35.setName("txt_sal"); // NOI18N
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Cancelar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jButton4.setName("btn_cancelar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("GERENTE");

        txt_nome.setForeground(new java.awt.Color(153, 153, 153));
        txt_nome.setText(" Nome");
        txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_nome.setEnabled(false);
        txt_nome.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_nome.setName("txt_nome"); // NOI18N
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomeFocusGained(evt);
            }
        });

        txt_rg.setForeground(new java.awt.Color(153, 153, 153));
        txt_rg.setText(" RG");
        txt_rg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_rg.setEnabled(false);
        txt_rg.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_rg.setName("txt_cpf"); // NOI18N
        txt_rg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rgFocusGained(evt);
            }
        });

        txt_nasc.setForeground(new java.awt.Color(153, 153, 153));
        txt_nasc.setText(" Data de nascimento: __/__/____");
        txt_nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_nasc.setEnabled(false);
        txt_nasc.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_nasc.setName("txt_nasc"); // NOI18N
        txt_nasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nascFocusGained(evt);
            }
        });
        txt_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nascActionPerformed(evt);
            }
        });

        txt_adm.setForeground(new java.awt.Color(153, 153, 153));
        txt_adm.setText(" Data de admissão: __/__/____");
        txt_adm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_adm.setEnabled(false);
        txt_adm.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_adm.setName("txt_admi"); // NOI18N
        txt_adm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_admFocusGained(evt);
            }
        });

        txt_sal.setForeground(new java.awt.Color(153, 153, 153));
        txt_sal.setText(" Salário");
        txt_sal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_sal.setEnabled(false);
        txt_sal.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_sal.setName("txt_sal"); // NOI18N
        txt_sal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_salFocusGained(evt);
            }
        });
        txt_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        txt_anos.setForeground(new java.awt.Color(153, 153, 153));
        txt_anos.setText(" Anos de experiência");
        txt_anos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_anos.setEnabled(false);
        txt_anos.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_anos.setName("txt_anos"); // NOI18N
        txt_anos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_anosFocusGained(evt);
            }
        });
        txt_anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anosActionPerformed(evt);
            }
        });

        txt_busca.setForeground(new java.awt.Color(153, 153, 153));
        txt_busca.setText(" Buscar pelo número do RG");
        txt_busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_busca.setEnabled(false);
        txt_busca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_busca.setName("txt_busca"); // NOI18N
        txt_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscaFocusGained(evt);
            }
        });

        btn_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar1.setEnabled(false);
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        btn_cadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setName("btn_cadastrar"); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(0, 102, 102));
        btn_alterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(255, 255, 255));
        btn_alterar.setText("Alterar");
        btn_alterar.setName("btn_cadastrar"); // NOI18N
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(0, 102, 102));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.setName("btn_cadastrar"); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 102, 102));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_cancelar.setName("btn_cancelar"); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(0, 102, 102));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Confirmar");
        btn_salvar.setEnabled(false);
        btn_salvar.setName("btn_salvar"); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        txt_email.setForeground(new java.awt.Color(153, 153, 153));
        txt_email.setText(" Email");
        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_email.setEnabled(false);
        txt_email.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_email.setName("txt_nome"); // NOI18N
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
        });

        txt_senha.setForeground(new java.awt.Color(153, 153, 153));
        txt_senha.setText(" Senha");
        txt_senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_senha.setEnabled(false);
        txt_senha.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_senha.setName("txt_cpf"); // NOI18N
        txt_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_senhaFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_anos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_rg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_anos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nascActionPerformed

    private void txt_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void txt_anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anosActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        //Verificar se achou o número, se achou fazer tudo aqui embaixo
        String rg;
        boolean flag = false;
        
        txt_nome.setText("");
        txt_rg.setText("");
        txt_anos.setText("");
        txt_nasc.setText("");
        txt_adm.setText("");
        txt_sal.setText("");
        txt_email.setText("");
        txt_senha.setText("");
        
        btn_salvar.setEnabled(true);
        txt_busca.setEnabled(false);
        btn_buscar1.setEnabled(false);

        //Carregar os dados aqui
        rg = txt_busca.getText();
        if(rg.isEmpty() || rg.equals("Buscar pelo número do RG"))
        {
            JOptionPane.showMessageDialog(null, "Insira o número do RG!", "Erro", JOptionPane.ERROR_MESSAGE);
            JFormCadastroGerente.this.setVisible(false);
        }
        
        else
        {
            try
            {
                FileReader arq = new FileReader(".//src//Model//gerente.txt");
                BufferedReader lerArq = new BufferedReader(arq);
                while(lerArq.ready() && flag == false)
                {
                    String linha = lerArq.readLine();
                    String[] dadoSeparado = linha.split(";");
                    if(dadoSeparado[0].equals(rg))
                    {
                        flag = true;
                        
                        txt_rg.setText(rg);
                        txt_nome.setText(dadoSeparado[1]);
                        txt_anos.setText(dadoSeparado[8]);
                        txt_nasc.setText(dadoSeparado[2]);
                        txt_adm.setText(dadoSeparado[3]);
                        txt_sal.setText(dadoSeparado[4]);
                        txt_email.setText(dadoSeparado[6]);
                        txt_senha.setText(dadoSeparado[7]);
                    }
                }
                
                lerArq.close();
                if(flag == false)
                     JOptionPane.showMessageDialog(null, "Número do RG não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
            catch(IOException e)
            {
                 JOptionPane.showMessageDialog(null, "Erro ao buscar dados no arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
                
        }

        if(this.btn_alterar.isEnabled())
        {
            txt_nome.setEnabled(true);
            txt_rg.setEnabled(false);
            txt_anos.setEnabled(true);
            txt_nasc.setEnabled(true);
            txt_adm.setEnabled(true);
            txt_sal.setEnabled(true);
            txt_email.setEnabled(true);
            txt_senha.setEnabled(true);
        }

        else if(this.btn_excluir.isEnabled())
        {
            txt_nome.setEnabled(false);
            txt_rg.setEnabled(false);
            txt_anos.setEnabled(false);
            txt_nasc.setEnabled(false);
            txt_adm.setEnabled(false);
            txt_sal.setEnabled(false);
            txt_email.setEnabled(false);
            txt_senha.setEnabled(false);
        }
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        txt_nome.setEnabled(true);
        txt_rg.setEnabled(true);
        txt_anos.setEnabled(true);
        txt_nasc.setEnabled(true);
        txt_adm.setEnabled(true);
        txt_sal.setEnabled(true);
        txt_email.setEnabled(true);
        txt_senha.setEnabled(true);

        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar1.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar1.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        JFormCadastroGerente.this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if((this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false) || (btn_cadastrar.isEnabled() == false && btn_excluir.isEnabled() == false))
        {
            String nome, rg, email, senha, data_nasc, data_adm;
            double salario;
            int anos;
            Data data = new Data();
            Data data1 = new Data();
            
            rg = txt_rg.getText();
            nome = txt_nome.getText();
            email = txt_email.getText();
            senha = txt_senha.getText();
            salario = Double.parseDouble(txt_sal.getText());
            anos = Integer.parseInt(txt_anos.getText());
            data_nasc = txt_nasc.getText();
            data_adm = txt_adm.getText();
            
            if(rg.isEmpty() || rg.equals("RG"))
                  JOptionPane.showMessageDialog(null, "Campo RG não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(nome.isEmpty() || nome.equals("Nome"))
                  JOptionPane.showMessageDialog(null, "Campo nome não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(email.isEmpty() || email.equals("Email") || email.contains("@") == false)
                JOptionPane.showMessageDialog(null, "Campo email não preenchido ou inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(nome.isEmpty() || nome.equals("Senha"))
                JOptionPane.showMessageDialog(null, "Campo senha não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(salario < 0)
                JOptionPane.showMessageDialog(null, "Salário inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(anos < 0)
                JOptionPane.showMessageDialog(null, "Anos de exp. inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(data_nasc.isEmpty() || data_nasc.equals("Data de nascimento: __/__/____"))
                JOptionPane.showMessageDialog(null, "Campo data de nascimento não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else if(data_adm.isEmpty() || data_adm.equals("Data de admissão: __/__/____"))
                JOptionPane.showMessageDialog(null, "Campo data de admissão não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
            
            else
            {
                data.setData(data_nasc);
                data1.setData(data_adm);
                
                Gerente gerente = new Gerente(rg, nome, data, data1, salario, email, senha, anos);
                if(this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false)
                {
                      gerente.cadastrar();
                      JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                }
                
                else
                {
                    gerente.alterar();
                    JOptionPane.showMessageDialog(null, "Gerente alterado com sucesso!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                }
            }
   
        }
        
        else if(btn_cadastrar.isEnabled() == false && btn_alterar.isEnabled() == false) //Excluir
        {
            Gerente gerente = new Gerente(txt_rg.getText());
            gerente.excluir();
            JOptionPane.showMessageDialog(null, "Gerente excluído com sucesso!", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
           
        }
        
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_salvar.setEnabled(false);
        
        Font fonte = new Font("Tahoma", Font.PLAIN, 11);
        
        txt_rg.setFont(fonte);
        txt_rg.setForeground(Color.LIGHT_GRAY);
        txt_nome.setFont(fonte);
        txt_nome.setForeground(Color.LIGHT_GRAY);
        txt_email.setFont(fonte);
        txt_email.setForeground(Color.LIGHT_GRAY);
        txt_senha.setFont(fonte);
        txt_senha.setForeground(Color.LIGHT_GRAY);
        txt_sal.setFont(fonte);
        txt_sal.setForeground(Color.LIGHT_GRAY);
        txt_anos.setFont(fonte);
        txt_anos.setForeground(Color.LIGHT_GRAY);
        txt_nasc.setFont(fonte);
        txt_nasc.setForeground(Color.LIGHT_GRAY);
        txt_adm.setFont(fonte);
        txt_adm.setForeground(Color.LIGHT_GRAY);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.LIGHT_GRAY);
        
        txt_rg.setText("RG");
        txt_nome.setText("Nome");
        txt_email.setText("Email");
        txt_senha.setText("Senha");
        txt_sal.setText("Salário");
        txt_anos.setText("Anos de experiência");
        txt_nasc.setText("Data de nascimento: __/__/____");
        txt_adm.setText("Data de admissão: __/__/____");
        txt_busca.setText("Buscar pelo número do RG");

        txt_rg.setEnabled(false);
        txt_nome.setEnabled(false);
        txt_email.setEnabled(false);
        txt_senha.setEnabled(false);
        txt_sal.setEnabled(false);
        txt_anos.setEnabled(false);
        txt_nasc.setEnabled(false);
        txt_adm.setEnabled(false);
        txt_busca.setEnabled(false);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscaFocusGained
        txt_busca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_buscaFocusGained

    private void txt_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusGained
        txt_nome.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_nome.setFont(fonte);
        txt_nome.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_nomeFocusGained

    private void txt_rgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rgFocusGained
        txt_rg.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_rg.setFont(fonte);
        txt_rg.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_rgFocusGained

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        txt_email.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_email.setFont(fonte);
        txt_email.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_senhaFocusGained
        txt_senha.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_senha.setFont(fonte);
        txt_senha.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_senhaFocusGained

    private void txt_nascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nascFocusGained
        txt_nasc.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_nasc.setFont(fonte);
        txt_nasc.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_nascFocusGained

    private void txt_admFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_admFocusGained
        txt_adm.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_adm.setFont(fonte);
        txt_adm.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_admFocusGained

    private void txt_salFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_salFocusGained
        txt_sal.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_sal.setFont(fonte);
        txt_sal.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_salFocusGained

    private void txt_anosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_anosFocusGained
        txt_anos.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_anos.setFont(fonte);
        txt_anos.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_anosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCadastroGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField txt_adm;
    private javax.swing.JTextField txt_anos;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nasc;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_sal;
    private javax.swing.JTextField txt_senha;
    // End of variables declaration//GEN-END:variables
}
