/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Controller.Carro;
import java.awt.Color;
import java.awt.Font;
import java.io.*;

/**
 *
 * @author sarah
 */
public class JFormCadastroCarro extends javax.swing.JFrame {

    /**
     * Creates new form JFormCadastroCarro
     */
    public JFormCadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField19 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_chassi = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_ano = new javax.swing.JTextField();
        txt_km = new javax.swing.JTextField();
        txt_combs = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        txt_potencia = new javax.swing.JTextField();
        txt_cilindros = new javax.swing.JTextField();
        txt_ocupantes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        txt_largura = new javax.swing.JTextField();
        txt_comp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        txt_busca = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText(" Marca");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField3.setMaximumSize(new java.awt.Dimension(17, 17));

        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText(" Número do chassi");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField4.setMaximumSize(new java.awt.Dimension(17, 17));

        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText(" Número do chassi");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField5.setMaximumSize(new java.awt.Dimension(17, 17));

        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText(" Número do chassi");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField6.setMaximumSize(new java.awt.Dimension(17, 17));

        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText(" Modelo");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField8.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField8.setName("txt_modelo"); // NOI18N

        jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        jTextField9.setText(" Modelo");
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField9.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField9.setName("txt_modelo"); // NOI18N

        jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        jTextField11.setText(" Ano");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField11.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField11.setName("txt_ano"); // NOI18N

        jTextField12.setForeground(new java.awt.Color(153, 153, 153));
        jTextField12.setText(" Ano");
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField12.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField12.setName("txt_ano"); // NOI18N

        jTextField13.setForeground(new java.awt.Color(153, 153, 153));
        jTextField13.setText(" Ano");
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField13.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField13.setName("txt_ano"); // NOI18N

        jTextField15.setForeground(new java.awt.Color(153, 153, 153));
        jTextField15.setText(" Ano");
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField15.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField15.setName("txt_ano"); // NOI18N

        jTextField17.setForeground(new java.awt.Color(153, 153, 153));
        jTextField17.setText(" Tipo de combustível");
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField17.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField17.setName("txt_combs"); // NOI18N

        jTextField18.setForeground(new java.awt.Color(153, 153, 153));
        jTextField18.setText(" Tipo de combustível");
        jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField18.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField18.setName("txt_combs"); // NOI18N

        jTextField19.setForeground(new java.awt.Color(153, 153, 153));
        jTextField19.setText(" Ano");
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField19.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField19.setName("txt_ano"); // NOI18N
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jTextField22.setForeground(new java.awt.Color(153, 153, 153));
        jTextField22.setText(" Ano");
        jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField22.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField22.setName("txt_ano"); // NOI18N
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton2.setText("utilitário");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jTextField20.setForeground(new java.awt.Color(153, 153, 153));
        jTextField20.setText(" Ano");
        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField20.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField20.setName("txt_ano"); // NOI18N
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jTextField27.setForeground(new java.awt.Color(153, 153, 153));
        jTextField27.setText(" Altura");
        jTextField27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField27.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField27.setName("txt_altura"); // NOI18N
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });

        jTextField29.setForeground(new java.awt.Color(153, 153, 153));
        jTextField29.setText(" Altura");
        jTextField29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField29.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField29.setName("txt_altura"); // NOI18N
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("A venda");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.setName("btn_cadastrar"); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Cancelar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jButton3.setName("btn_cancelar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("CARRO");

        txt_chassi.setForeground(new java.awt.Color(153, 153, 153));
        txt_chassi.setText(" Número do chassi");
        txt_chassi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_chassi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_chassi.setEnabled(false);
        txt_chassi.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_chassi.setName("txt_chassi"); // NOI18N
        txt_chassi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_chassiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_chassiFocusLost(evt);
            }
        });

        txt_marca.setForeground(new java.awt.Color(153, 153, 153));
        txt_marca.setText(" Marca");
        txt_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_marca.setEnabled(false);
        txt_marca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_marca.setName("txt_marca"); // NOI18N
        txt_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_marcaFocusGained(evt);
            }
        });

        txt_modelo.setForeground(new java.awt.Color(153, 153, 153));
        txt_modelo.setText(" Modelo");
        txt_modelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_modelo.setEnabled(false);
        txt_modelo.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_modelo.setName("txt_modelo"); // NOI18N
        txt_modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_modeloFocusGained(evt);
            }
        });

        txt_ano.setForeground(new java.awt.Color(153, 153, 153));
        txt_ano.setText(" Ano");
        txt_ano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_ano.setEnabled(false);
        txt_ano.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_ano.setName("txt_ano"); // NOI18N
        txt_ano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_anoFocusGained(evt);
            }
        });
        txt_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anoActionPerformed(evt);
            }
        });

        txt_km.setForeground(new java.awt.Color(153, 153, 153));
        txt_km.setText(" Km");
        txt_km.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_km.setEnabled(false);
        txt_km.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_km.setName("txt_km"); // NOI18N
        txt_km.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_kmFocusGained(evt);
            }
        });

        txt_combs.setForeground(new java.awt.Color(153, 153, 153));
        txt_combs.setText(" Tipo de combustível");
        txt_combs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_combs.setEnabled(false);
        txt_combs.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_combs.setName("txt_combs"); // NOI18N
        txt_combs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_combsFocusGained(evt);
            }
        });

        txt_peso.setForeground(new java.awt.Color(153, 153, 153));
        txt_peso.setText(" Peso");
        txt_peso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_peso.setEnabled(false);
        txt_peso.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_peso.setName("txt_peso"); // NOI18N
        txt_peso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pesoFocusGained(evt);
            }
        });
        txt_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesoActionPerformed(evt);
            }
        });

        txt_potencia.setForeground(new java.awt.Color(153, 153, 153));
        txt_potencia.setText(" Potência");
        txt_potencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_potencia.setEnabled(false);
        txt_potencia.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_potencia.setName("txt_pot"); // NOI18N
        txt_potencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_potenciaFocusGained(evt);
            }
        });
        txt_potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_potenciaActionPerformed(evt);
            }
        });

        txt_cilindros.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_cilindros.setForeground(new java.awt.Color(153, 153, 153));
        txt_cilindros.setText(" Número de cilindros");
        txt_cilindros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_cilindros.setEnabled(false);
        txt_cilindros.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_cilindros.setName("txt_cilindros"); // NOI18N
        txt_cilindros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cilindrosFocusGained(evt);
            }
        });
        txt_cilindros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cilindrosActionPerformed(evt);
            }
        });

        txt_ocupantes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_ocupantes.setForeground(new java.awt.Color(153, 153, 153));
        txt_ocupantes.setText(" Número de ocupantes");
        txt_ocupantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_ocupantes.setEnabled(false);
        txt_ocupantes.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_ocupantes.setName("txt_ocupantes"); // NOI18N
        txt_ocupantes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ocupantesFocusGained(evt);
            }
        });
        txt_ocupantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ocupantesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Tipo");

        cmb_tipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilitário", "Pickup", "Sedan", "Hatch", "Esportivo" }));
        cmb_tipo.setToolTipText("");
        cmb_tipo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Status");

        txt_altura.setForeground(new java.awt.Color(153, 153, 153));
        txt_altura.setText(" Altura");
        txt_altura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_altura.setEnabled(false);
        txt_altura.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_altura.setName("txt_altura"); // NOI18N
        txt_altura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_alturaFocusGained(evt);
            }
        });
        txt_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alturaActionPerformed(evt);
            }
        });

        txt_largura.setForeground(new java.awt.Color(153, 153, 153));
        txt_largura.setText(" Largura");
        txt_largura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_largura.setEnabled(false);
        txt_largura.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_largura.setName("txt_largura"); // NOI18N
        txt_largura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_larguraFocusGained(evt);
            }
        });
        txt_largura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_larguraActionPerformed(evt);
            }
        });

        txt_comp.setForeground(new java.awt.Color(153, 153, 153));
        txt_comp.setText(" Comprimento");
        txt_comp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_comp.setEnabled(false);
        txt_comp.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_comp.setName("txt_comprimento"); // NOI18N
        txt_comp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_compFocusGained(evt);
            }
        });
        txt_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_compActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Dimensões");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        txt_status.setEditable(false);
        txt_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_status.setText("A venda");
        txt_status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_status.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_status.setName("txt_combs"); // NOI18N

        btn_cadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setName("btn_cadastrar"); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(0, 102, 102));
        btn_alterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(255, 255, 255));
        btn_alterar.setText("Alterar");
        btn_alterar.setName("btn_cadastrar"); // NOI18N
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(0, 102, 102));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.setName("btn_cadastrar"); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 102, 102));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_cancelar.setName("btn_cancelar"); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(0, 102, 102));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Confirmar");
        btn_salvar.setEnabled(false);
        btn_salvar.setName("btn_salvar"); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        txt_busca.setForeground(new java.awt.Color(153, 153, 153));
        txt_busca.setText(" Buscar pelo número do chassi");
        txt_busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_busca.setEnabled(false);
        txt_busca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_busca.setName("txt_busca"); // NOI18N
        txt_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscaFocusGained(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar.setEnabled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_chassi, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                            .addComponent(txt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 58, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_salvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_largura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_combs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txt_cilindros, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                    .addComponent(txt_peso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_potencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txt_ocupantes, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))))
                                .addGap(20, 20, 20))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_combs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ocupantes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(txt_largura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anoActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void txt_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesoActionPerformed

    private void txt_potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_potenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_potenciaActionPerformed

    private void txt_cilindrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cilindrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cilindrosActionPerformed

    private void txt_ocupantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ocupantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ocupantesActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void txt_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alturaActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void txt_larguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_larguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_larguraActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void txt_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_compActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        txt_status.setText("A venda");
        txt_chassi.setEnabled(true);
        txt_marca.setEnabled(true);
        txt_modelo.setEnabled(true);
        txt_ano.setEnabled(true);
        txt_km.setEnabled(true);
        txt_combs.setEnabled(true);
        txt_peso.setEnabled(true);
        txt_potencia.setEnabled(true);
        txt_cilindros.setEnabled(true);
        txt_ocupantes.setEnabled(true);
        txt_altura.setEnabled(true);
        txt_comp.setEnabled(true);
        txt_largura.setEnabled(true);
        cmb_tipo.setEnabled(true);
        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        JFormCadastroCarro.this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String chassi;
        boolean flag = false;
        
        txt_chassi.setText("");
        txt_marca.setText("");
        txt_modelo.setText("");
        txt_ano.setText("");
        txt_km.setText("");
        txt_combs.setText("");
        txt_peso.setText("");
        txt_cilindros.setText("");
        txt_potencia.setText("");
        txt_ocupantes.setText("");
        txt_altura.setText("");
        txt_comp.setText("");
        txt_largura.setText("");
        txt_status.setText("");

        btn_salvar.setEnabled(true);
        txt_busca.setEnabled(false);
        btn_buscar.setEnabled(false);
        
        chassi = txt_busca.getText();
        if(chassi.isEmpty())
            JOptionPane.showMessageDialog(null, "Insira o número do chassi!", "Erro", JOptionPane.ERROR_MESSAGE);
        else
        {
            try
            {
                FileReader arq = new FileReader(".//src//Model//carros.txt");
                BufferedReader lerArq = new BufferedReader(arq);
                while(lerArq.ready() && flag == false)
                {
                    String linha = lerArq.readLine();
                    String[] dadoSeparado = linha.split(";");
                    if(dadoSeparado[0].equals(chassi))
                    {
                        flag = true;
                        
                        txt_chassi.setText(chassi);
                        txt_marca.setText(dadoSeparado[1]);
                        txt_modelo.setText(dadoSeparado[2]);
                        txt_ano.setText(dadoSeparado[3]);
                        txt_km.setText(dadoSeparado[4]);
                        txt_combs.setText(dadoSeparado[5]);
                        txt_peso.setText(dadoSeparado[6]);
                        txt_status.setText(dadoSeparado[7]);
                        txt_potencia.setText(dadoSeparado[8]);
                        txt_cilindros.setText(dadoSeparado[9]);
                        txt_ocupantes.setText(dadoSeparado[10]);
                        cmb_tipo.setSelectedItem(dadoSeparado[11]);
                        txt_altura.setText(dadoSeparado[12]);
                        txt_largura.setText(dadoSeparado[13]);
                        txt_comp.setText(dadoSeparado[14]);
                    }
                }

                lerArq.close();
                if(flag == false)
                     JOptionPane.showMessageDialog(null, "Número do chassi não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados no arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(this.btn_alterar.isEnabled())
        {
            txt_chassi.setEnabled(false);
            txt_marca.setEnabled(true);
            txt_modelo.setEnabled(true);
            txt_ano.setEnabled(true);
            txt_km.setEnabled(true);
            txt_combs.setEnabled(true);
            txt_peso.setEnabled(true);
            txt_potencia.setEnabled(true);
            txt_cilindros.setEnabled(true);
            txt_ocupantes.setEnabled(true);
            txt_altura.setEnabled(true);
            txt_comp.setEnabled(true);
            txt_largura.setEnabled(true);
            cmb_tipo.setEnabled(true);
        }

        else if(this.btn_excluir.isEnabled())
        {
            txt_chassi.setEnabled(false);
            txt_marca.setEnabled(false);
            txt_modelo.setEnabled(false);
            txt_ano.setEnabled(false);
            txt_km.setEnabled(false);
            txt_combs.setEnabled(false);
            txt_peso.setEnabled(false);
            txt_potencia.setEnabled(false);
            txt_cilindros.setEnabled(false);
            txt_ocupantes.setEnabled(false);
            txt_altura.setEnabled(false);
            txt_comp.setEnabled(false);
            txt_largura.setEnabled(false);
            cmb_tipo.setEnabled(false);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
       
        if((this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false) || (btn_cadastrar.isEnabled() == false && btn_excluir.isEnabled() == false)) 
        {
           String chassi, marca, modelo, tipo, status, tipoCombustivel;
           int ano, numCilindros, numOcupantes, potencia;
           double km, peso, altura, comprimento, largura;
           
           //Pega os dados
           chassi = txt_chassi.getText();
           marca = txt_marca.getText();
           modelo = txt_modelo.getText();
           tipo = cmb_tipo.getSelectedItem().toString();
           status = txt_status.getText();
           tipoCombustivel = txt_combs.getText();
           ano = Integer.parseInt(txt_ano.getText());
           numCilindros = Integer.parseInt(txt_cilindros.getText());
           numOcupantes = Integer.parseInt(txt_ocupantes.getText());
           potencia = Integer.parseInt(txt_potencia.getText());
           km = Double.parseDouble(txt_km.getText());
           peso = Double.parseDouble(txt_peso.getText());
           altura = Double.parseDouble(txt_altura.getText());
           comprimento = Double.parseDouble(txt_comp.getText());
           largura = Double.parseDouble(txt_largura.getText());
           
           //Confere
           if(chassi.isEmpty() || chassi.equals("Número do Chassi"))
               JOptionPane.showMessageDialog(null, "Campo chassi não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(marca.isEmpty() || marca.equals("Marca"))
               JOptionPane.showMessageDialog(null, "Campo marca não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(modelo.isEmpty() || modelo.equals("Modelo"))
               JOptionPane.showMessageDialog(null, "Campo modelo não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(tipoCombustivel.isEmpty() || tipoCombustivel.equals("Tipo de combustível"))
               JOptionPane.showMessageDialog(null, "Campo combustível não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(ano < 1950 || ano > 2050)
               JOptionPane.showMessageDialog(null, "Ano inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(numCilindros < 1 || numCilindros > 10)
               JOptionPane.showMessageDialog(null, "Número de cilindros inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(numOcupantes < 1 || numOcupantes > 10)
               JOptionPane.showMessageDialog(null, "Número de ocupantes inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(potencia < 0)
               JOptionPane.showMessageDialog(null, "Potência inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(km < 0)
               JOptionPane.showMessageDialog(null, "Km inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(peso < 0 || peso > 10000)
               JOptionPane.showMessageDialog(null, "Peso inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(altura < 1)
               JOptionPane.showMessageDialog(null, "Altura inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(comprimento < 1)
               JOptionPane.showMessageDialog(null, "Comprimento inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(largura < 1)
               JOptionPane.showMessageDialog(null, "Largura inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
           else
           {
               //Cria objeto 
               Carro carro = new Carro(potencia, numCilindros, numOcupantes, tipo, altura, largura, comprimento, chassi, marca, modelo, ano, km, tipoCombustivel, peso, status);
               if(this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false)
               {
                   carro.cadastrar();
                   JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                   
               }
               
               else //Alterar
               {
                  carro.alterar();
                  JOptionPane.showMessageDialog(null, "Veículo alterado com sucesso!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                  
               }
           }
       }
       
       else if(btn_cadastrar.isEnabled() == false && btn_alterar.isEnabled() == false) //Excluir
       {
           Carro carro = new Carro(txt_chassi.getText());
           carro.excluir();
           JOptionPane.showMessageDialog(null, "Veículo excluído com sucesso!", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
           
       }
        
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_salvar.setEnabled(false);
     
       //Limpa os campos
       Font fonte = new Font("Tahoma", Font.PLAIN, 11);
       
       txt_chassi.setFont(fonte);
       txt_chassi.setForeground(Color.LIGHT_GRAY);
       txt_marca.setFont(fonte);
       txt_marca.setForeground(Color.LIGHT_GRAY);
       txt_modelo.setFont(fonte);
       txt_modelo.setForeground(Color.LIGHT_GRAY);
       txt_ano.setFont(fonte);
       txt_ano.setForeground(Color.LIGHT_GRAY);
       txt_km.setFont(fonte);
       txt_km.setForeground(Color.LIGHT_GRAY);
       txt_combs.setFont(fonte);
       txt_combs.setForeground(Color.LIGHT_GRAY);
       txt_peso.setFont(fonte);
       txt_peso.setForeground(Color.LIGHT_GRAY);
       txt_potencia.setFont(fonte);
       txt_potencia.setForeground(Color.LIGHT_GRAY);
       txt_cilindros.setFont(fonte);
       txt_cilindros.setForeground(Color.LIGHT_GRAY);
       txt_ocupantes.setFont(fonte);
       txt_ocupantes.setForeground(Color.LIGHT_GRAY);
       txt_altura.setFont(fonte);
       txt_altura.setForeground(Color.LIGHT_GRAY);
       txt_comp.setFont(fonte);
       txt_comp.setForeground(Color.LIGHT_GRAY);
       txt_largura.setFont(fonte);
       txt_largura.setForeground(Color.LIGHT_GRAY);
       txt_busca.setFont(fonte);
       txt_busca.setForeground(Color.LIGHT_GRAY);
       
       txt_chassi.setText("Número do Chassi");
       txt_marca.setText("Marca");
       txt_modelo.setText("Modelo");
       txt_ano.setText("Ano");
       txt_km.setText("Km");
       txt_combs.setText("Tipo de combustível");
       txt_peso.setText("Peso");
       txt_potencia.setText("Potência");
       txt_cilindros.setText("Cilindros");
       txt_ocupantes.setText("Ocupantes");
       txt_altura.setText("Altura");
       txt_comp.setText("Comprimento");
       txt_largura.setText("Largura");
       txt_busca.setText("Buscar pelo número do chassi");
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_chassiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_chassiFocusGained
        txt_chassi.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_chassi.setFont(fonte);
        txt_chassi.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_chassiFocusGained

    private void txt_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscaFocusGained
        txt_busca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_buscaFocusGained

    private void txt_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusGained
        txt_marca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_marca.setFont(fonte);
        txt_marca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_marcaFocusGained

    private void txt_modeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_modeloFocusGained
        txt_modelo.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_modelo.setFont(fonte);
        txt_modelo.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_modeloFocusGained

    private void txt_anoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_anoFocusGained
        txt_ano.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_ano.setFont(fonte);
        txt_ano.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_anoFocusGained

    private void txt_kmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_kmFocusGained
        txt_km.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_km.setFont(fonte);
        txt_km.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_kmFocusGained

    private void txt_combsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_combsFocusGained
        txt_combs.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_combs.setFont(fonte);
        txt_combs.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_combsFocusGained

    private void txt_pesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pesoFocusGained
        txt_peso.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_peso.setFont(fonte);
        txt_peso.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_pesoFocusGained

    private void txt_potenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_potenciaFocusGained
        txt_potencia.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_potencia.setFont(fonte);
        txt_potencia.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_potenciaFocusGained

    private void txt_cilindrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cilindrosFocusGained
        txt_cilindros.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_cilindros.setFont(fonte);
        txt_cilindros.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_cilindrosFocusGained

    private void txt_ocupantesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ocupantesFocusGained
        txt_ocupantes.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_ocupantes.setFont(fonte);
        txt_ocupantes.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_ocupantesFocusGained

    private void txt_alturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alturaFocusGained
        txt_altura.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_altura.setFont(fonte);
        txt_altura.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_alturaFocusGained

    private void txt_compFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_compFocusGained
        txt_comp.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_comp.setFont(fonte);
        txt_comp.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_compFocusGained

    private void txt_larguraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_larguraFocusGained
        txt_largura.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_largura.setFont(fonte);
        txt_largura.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_larguraFocusGained

    private void txt_chassiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_chassiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chassiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_chassi;
    private javax.swing.JTextField txt_cilindros;
    private javax.swing.JTextField txt_combs;
    private javax.swing.JTextField txt_comp;
    private javax.swing.JTextField txt_km;
    private javax.swing.JTextField txt_largura;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_ocupantes;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_potencia;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
