/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Cliente;
import Controller.Data;
import Controller.Endereco;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author sarah
 */
public class JFormCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFormCadastroCliente
     */
    public JFormCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField45 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        txt_rua = new javax.swing.JTextField();
        txt_nasc = new javax.swing.JTextField();
        txt_dependentes = new javax.swing.JTextField();
        txt_renda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_busca = new javax.swing.JTextField();
        btn_buscar1 = new javax.swing.JButton();

        jTextField45.setForeground(new java.awt.Color(153, 153, 153));
        jTextField45.setText(" Bairro");
        jTextField45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField45.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField45.setName("txt_bairro"); // NOI18N
        jTextField45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField45ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("CLIENTE");

        txt_nome.setForeground(new java.awt.Color(153, 153, 153));
        txt_nome.setText(" Nome");
        txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_nome.setEnabled(false);
        txt_nome.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_nome.setName("txt_nome"); // NOI18N
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomeFocusGained(evt);
            }
        });

        txt_cpf.setForeground(new java.awt.Color(153, 153, 153));
        txt_cpf.setText(" CPF");
        txt_cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_cpf.setEnabled(false);
        txt_cpf.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_cpf.setName("txt_cpf"); // NOI18N
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cpfFocusGained(evt);
            }
        });

        txt_rua.setForeground(new java.awt.Color(153, 153, 153));
        txt_rua.setText(" Rua");
        txt_rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_rua.setEnabled(false);
        txt_rua.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_rua.setName("txt_rua"); // NOI18N
        txt_rua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ruaFocusGained(evt);
            }
        });

        txt_nasc.setForeground(new java.awt.Color(153, 153, 153));
        txt_nasc.setText(" Data de nascimento: __/__/____");
        txt_nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_nasc.setEnabled(false);
        txt_nasc.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_nasc.setName("txt_nasc"); // NOI18N
        txt_nasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nascFocusGained(evt);
            }
        });
        txt_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nascActionPerformed(evt);
            }
        });

        txt_dependentes.setForeground(new java.awt.Color(153, 153, 153));
        txt_dependentes.setText(" Dependentes");
        txt_dependentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_dependentes.setEnabled(false);
        txt_dependentes.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_dependentes.setName("txt_dependentes"); // NOI18N
        txt_dependentes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dependentesFocusGained(evt);
            }
        });

        txt_renda.setForeground(new java.awt.Color(153, 153, 153));
        txt_renda.setText(" Renda");
        txt_renda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_renda.setEnabled(false);
        txt_renda.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_renda.setName("txt_renda"); // NOI18N
        txt_renda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rendaFocusGained(evt);
            }
        });
        txt_renda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rendaActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        txt_bairro.setForeground(new java.awt.Color(153, 153, 153));
        txt_bairro.setText(" Bairro");
        txt_bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_bairro.setEnabled(false);
        txt_bairro.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_bairro.setName("txt_bairro"); // NOI18N
        txt_bairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_bairroFocusGained(evt);
            }
        });
        txt_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bairroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Endereço");

        txt_cidade.setForeground(new java.awt.Color(153, 153, 153));
        txt_cidade.setText(" Cidade");
        txt_cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_cidade.setEnabled(false);
        txt_cidade.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_cidade.setName("txt_cidade"); // NOI18N
        txt_cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cidadeFocusGained(evt);
            }
        });
        txt_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cidadeActionPerformed(evt);
            }
        });

        txt_num.setForeground(new java.awt.Color(153, 153, 153));
        txt_num.setText(" Número");
        txt_num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_num.setEnabled(false);
        txt_num.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_num.setName("txt_num"); // NOI18N
        txt_num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_numFocusGained(evt);
            }
        });
        txt_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(0, 102, 102));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Confirmar");
        btn_salvar.setEnabled(false);
        btn_salvar.setName("btn_salvar"); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setName("btn_cadastrar"); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(0, 102, 102));
        btn_alterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(255, 255, 255));
        btn_alterar.setText("Alterar");
        btn_alterar.setName("btn_cadastrar"); // NOI18N
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(0, 102, 102));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.setName("btn_cadastrar"); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 102, 102));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_cancelar.setName("btn_cancelar"); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txt_busca.setForeground(new java.awt.Color(153, 153, 153));
        txt_busca.setText(" Buscar pelo número do CPF");
        txt_busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_busca.setEnabled(false);
        txt_busca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_busca.setName("txt_busca"); // NOI18N
        txt_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscaFocusGained(evt);
            }
        });

        btn_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar1.setEnabled(false);
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)
                        .addGap(68, 68, 68)
                        .addComponent(btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                .addComponent(txt_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_dependentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_renda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_cidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_rua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_renda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nascActionPerformed

    private void txt_rendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rendaActionPerformed

    private void txt_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bairroActionPerformed

    private void jTextField45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField45ActionPerformed

    private void txt_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cidadeActionPerformed

    private void txt_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        txt_nome.setEnabled(true);
        txt_cpf.setEnabled(true);
        txt_dependentes.setEnabled(true);
        txt_nasc.setEnabled(true);
        txt_renda.setEnabled(true);
        txt_rua.setEnabled(true);
        txt_num.setEnabled(true);
        txt_bairro.setEnabled(true);
        txt_cidade.setEnabled(true);

        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar1.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar1.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        JFormCadastroCliente.this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        //Verificar se achou o número, se achou fazer tudo aqui embaixo
        String cpf;
        boolean flag = false;
        
        txt_nome.setText("");
        txt_cpf.setText("");
        txt_dependentes.setText("");
        txt_nasc.setText("");
        txt_renda.setText("");
        txt_rua.setText("");
        txt_num.setText("");
        txt_bairro.setText("");
        txt_cidade.setText("");

        btn_salvar.setEnabled(true);
        txt_busca.setEnabled(false);
        btn_buscar1.setEnabled(false);

        cpf = txt_busca.getText();
        
        if(cpf.isEmpty() || cpf.equals("Buscar pelo número do CPF"))
        {
            JOptionPane.showMessageDialog(null, "Insira o número do CPF!", "Erro", JOptionPane.ERROR_MESSAGE);
            JFormCadastroCliente.this.setVisible(false);
        }
        else
        {
            try
            {
                FileReader arq = new FileReader(".//src//Model//clientes.txt");
                BufferedReader lerArq = new BufferedReader(arq);
                while(lerArq.ready() && flag == false)
                {
                    String linha = lerArq.readLine();
                    String[] dadoSeparado = linha.split(";");
                    if(dadoSeparado[0].equals(cpf))
                    {
                        flag = true;
                        
                        txt_cpf.setText(cpf);
                        txt_nome.setText(dadoSeparado[1]);
                        txt_nasc.setText(dadoSeparado[2]);
                        txt_renda.setText(dadoSeparado[3]);
                        txt_dependentes.setText(dadoSeparado[4]);
                        txt_cidade.setText(dadoSeparado[5]);
                        txt_bairro.setText(dadoSeparado[6]);
                        txt_rua.setText(dadoSeparado[7]);
                        txt_num.setText(dadoSeparado[8]);
      
                    }
                }

                lerArq.close();
                if(flag == false)
                     JOptionPane.showMessageDialog(null, "Número do CPF não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);

            }
            
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados no arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
        if(this.btn_alterar.isEnabled())
        {
            txt_nome.setEnabled(true);
            txt_cpf.setEnabled(false);
            txt_dependentes.setEnabled(true);
            txt_nasc.setEnabled(true);
            txt_renda.setEnabled(true);
            txt_rua.setEnabled(true);
            txt_num.setEnabled(true);
            txt_bairro.setEnabled(true);
            txt_cidade.setEnabled(true);
        }

        else if(this.btn_excluir.isEnabled())
        {
            txt_nome.setEnabled(false);
            txt_cpf.setEnabled(false);
            txt_dependentes.setEnabled(false);
            txt_nasc.setEnabled(false);
            txt_renda.setEnabled(false);
            txt_rua.setEnabled(false);
            txt_num.setEnabled(false);
            txt_bairro.setEnabled(false);
            txt_cidade.setEnabled(false);
        }
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void txt_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscaFocusGained
        txt_busca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_buscaFocusGained

    private void txt_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusGained
        txt_nome.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_nome.setFont(fonte);
        txt_nome.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_nomeFocusGained

    private void txt_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusGained
        txt_cpf.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_cpf.setFont(fonte);
        txt_cpf.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_cpfFocusGained

    private void txt_ruaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ruaFocusGained
        txt_rua.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_rua.setFont(fonte);
        txt_rua.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_ruaFocusGained

    private void txt_numFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_numFocusGained
        txt_num.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_num.setFont(fonte);
        txt_num.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_numFocusGained

    private void txt_bairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bairroFocusGained
        txt_bairro.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_bairro.setFont(fonte);
        txt_bairro.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_bairroFocusGained

    private void txt_cidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cidadeFocusGained
        txt_cidade.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_cidade.setFont(fonte);
        txt_cidade.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_cidadeFocusGained

    private void txt_nascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nascFocusGained
        txt_nasc.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_nasc.setFont(fonte);
        txt_nasc.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_nascFocusGained

    private void txt_dependentesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dependentesFocusGained
        txt_dependentes.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_dependentes.setFont(fonte);
        txt_dependentes.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_dependentesFocusGained

    private void txt_rendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rendaFocusGained
        txt_renda.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_renda.setFont(fonte);
        txt_renda.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_rendaFocusGained

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
         if((this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false) || (btn_cadastrar.isEnabled() == false && btn_excluir.isEnabled() == false))
         {
             String nome, cpf, dataN, cidade, rua, bairro;
             int dependentes, num;
             double renda;
             Data data = new Data();
             Endereco end = new Endereco();
             
             cpf = txt_cpf.getText();
             nome = txt_nome.getText();
             dataN = txt_nasc.getText();
             dependentes = Integer.parseInt(txt_dependentes.getText());
             renda = Double.parseDouble(txt_cpf.getText());
             cidade = txt_cidade.getText();
             rua = txt_rua.getText();
             bairro = txt_bairro.getText();
             num = Integer.parseInt(txt_num.getText());
             
             if(cpf.isEmpty() || cpf.equals("CPF"))
               JOptionPane.showMessageDialog(null, "Campo CPF não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(nome.isEmpty() || nome.equals("Nome"))
                 JOptionPane.showMessageDialog(null, "Campo nome não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(dataN.isEmpty() || dataN.equals(" Data de nascimento: __/__/____"))
                 JOptionPane.showMessageDialog(null, "Campo data de nascimento não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(cidade.isEmpty() || cidade.equals("Cidade"))
                 JOptionPane.showMessageDialog(null, "Campo cidade não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(rua.isEmpty() || rua.equals("Rua"))
                 JOptionPane.showMessageDialog(null, "Campo rua não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(bairro.isEmpty() || bairro.equals("Bairro"))
                 JOptionPane.showMessageDialog(null, "Campo bairro não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(dependentes < 0)
                  JOptionPane.showMessageDialog(null, "Número de dependentes inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(renda < 0)
                  JOptionPane.showMessageDialog(null, "Renda inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
             
             else if(num < 0)
                 JOptionPane.showMessageDialog(null, "Número da residência inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
              
             else
             {
                 data.setData(dataN);
                 end.setEndCidade(cidade);
                 end.setEndBairro(bairro);
                 end.setEndRua(rua);
                 end.setEndNum(num);
                 
                 Cliente cliente = new Cliente(cpf, nome, renda, dependentes, data, end);
                 if(this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false)
                 {
                     cliente.cadastrar();
                     JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE); 
                 }
                 
                 else
                 {
                   cliente.alterar();
                   JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                 }

             }
         }
         
         else if(btn_cadastrar.isEnabled() == false && btn_alterar.isEnabled() == false) //Excluir
         {
            Cliente cliente = new Cliente(txt_cpf.getText());
            cliente.excluir();
            JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!", "Exclusão", JOptionPane.INFORMATION_MESSAGE); 
         }
         
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_salvar.setEnabled(false);
        
        Font fonte = new Font("Tahoma", Font.PLAIN, 11);
        
        txt_cpf.setFont(fonte);
        txt_cpf.setForeground(Color.LIGHT_GRAY);
        txt_nome.setFont(fonte);
        txt_nome.setForeground(Color.LIGHT_GRAY);
        txt_dependentes.setFont(fonte);
        txt_dependentes.setForeground(Color.LIGHT_GRAY);
        txt_renda.setFont(fonte);
        txt_renda.setForeground(Color.LIGHT_GRAY);
        txt_nasc.setFont(fonte);
        txt_nasc.setForeground(Color.LIGHT_GRAY);
        txt_cidade.setFont(fonte);
        txt_cidade.setForeground(Color.LIGHT_GRAY);
        txt_bairro.setFont(fonte);
        txt_bairro.setForeground(Color.LIGHT_GRAY);
        txt_rua.setFont(fonte);
        txt_rua.setForeground(Color.LIGHT_GRAY);
        txt_num.setFont(fonte);
        txt_num.setForeground(Color.LIGHT_GRAY);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.LIGHT_GRAY);
        
        txt_cpf.setText("CPF");
        txt_nome.setText("Nome");
        txt_dependentes.setText("Dependentes");
        txt_renda.setText("Renda");
        txt_nasc.setText("Data de nascimento: __/__/____");
        txt_rua.setText("Rua");
        txt_num.setText("Número");
        txt_bairro.setText("Bairro");
        txt_cidade.setText("Cidade");
        txt_busca.setText("Buscar pelo número do CPF");
        
        txt_cpf.setEnabled(false);
        txt_nome.setEnabled(false);
        txt_dependentes.setEnabled(false);
        txt_renda.setEnabled(false);
        txt_nasc.setEnabled(false);
        txt_rua.setEnabled(false);
        txt_num.setEnabled(false);
        txt_bairro.setEnabled(false);
        txt_cidade.setEnabled(false);
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_dependentes;
    private javax.swing.JTextField txt_nasc;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_renda;
    private javax.swing.JTextField txt_rua;
    // End of variables declaration//GEN-END:variables
}
