/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Controller.Motocicleta;
import java.awt.Color;
import java.awt.Font;
import java.io.*;

/**
 *
 * @author sarah
 */
public class JFormCadastroMoto extends javax.swing.JFrame {

    /**
     * Creates new form JFormCadastroMoto
     */
    public JFormCadastroMoto() {
        initComponents();
        
        int cont=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField24 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_cilindradas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_chassi = new javax.swing.JTextField();
        cmb_tipo = new javax.swing.JComboBox<>();
        txt_marca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        txt_ano = new javax.swing.JTextField();
        txt_km = new javax.swing.JTextField();
        txt_combs = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        txt_status = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        txt_busca = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton1.setText("A venda");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jTextField24.setForeground(new java.awt.Color(153, 153, 153));
        jTextField24.setText(" Potência");
        jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField24.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField24.setName("txt_pot"); // NOI18N
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton4.setText("Vendido");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(153, 153, 153));
        jTextField25.setText(" Número de cilindros");
        jTextField25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField25.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField25.setName("txt_cilindros"); // NOI18N
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });

        jTextField26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField26.setForeground(new java.awt.Color(153, 153, 153));
        jTextField26.setText(" Número de ocupantes");
        jTextField26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField26.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField26.setName("txt_ocupantes"); // NOI18N
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Cadastro - CARRO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Tipo");

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText(" Número do chassi");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField1.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField1.setName("txt_chassi"); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "utilitário", "pickup", "sedan", "hatch", "esportivo" }));
        jComboBox1.setToolTipText("");

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText(" Marca");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField2.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField2.setName("txt_marca"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Status");

        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText(" Modelo");
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField7.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField7.setName("txt_modelo"); // NOI18N

        jTextField21.setForeground(new java.awt.Color(153, 153, 153));
        jTextField21.setText(" Altura");
        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField21.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField21.setName("txt_altura"); // NOI18N
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        jTextField10.setText(" Ano");
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField10.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField10.setName("txt_ano"); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField28.setForeground(new java.awt.Color(153, 153, 153));
        jTextField28.setText(" Largura");
        jTextField28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField28.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField28.setName("txt_largura"); // NOI18N
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });

        jTextField14.setForeground(new java.awt.Color(153, 153, 153));
        jTextField14.setText(" Km");
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField14.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField14.setName("txt_km"); // NOI18N

        jTextField30.setForeground(new java.awt.Color(153, 153, 153));
        jTextField30.setText(" Comprimento");
        jTextField30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField30.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField30.setName("txt_comprimento"); // NOI18N
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });

        jTextField16.setForeground(new java.awt.Color(153, 153, 153));
        jTextField16.setText(" Tipo de combustível");
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField16.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField16.setName("txt_combs"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Dimensões");

        jTextField23.setForeground(new java.awt.Color(153, 153, 153));
        jTextField23.setText(" Peso");
        jTextField23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTextField23.setMaximumSize(new java.awt.Dimension(17, 17));
        jTextField23.setName("txt_peso"); // NOI18N
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cadastrar");
        jButton6.setName("btn_cadastrar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        txt_cilindradas.setForeground(new java.awt.Color(153, 153, 153));
        txt_cilindradas.setText(" Cilindradas");
        txt_cilindradas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_cilindradas.setEnabled(false);
        txt_cilindradas.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_cilindradas.setName("txt_cilindradas"); // NOI18N
        txt_cilindradas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cilindradasFocusGained(evt);
            }
        });
        txt_cilindradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cilindradasActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("MOTO");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Tipo");

        txt_chassi.setForeground(new java.awt.Color(153, 153, 153));
        txt_chassi.setText(" Número do chassi");
        txt_chassi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_chassi.setEnabled(false);
        txt_chassi.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_chassi.setName("txt_chassi"); // NOI18N
        txt_chassi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_chassiFocusGained(evt);
            }
        });
        txt_chassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chassiActionPerformed(evt);
            }
        });

        cmb_tipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trail", "Street", "Esportiva", "Custom" }));
        cmb_tipo.setToolTipText("");
        cmb_tipo.setEnabled(false);

        txt_marca.setForeground(new java.awt.Color(153, 153, 153));
        txt_marca.setText(" Marca");
        txt_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_marca.setEnabled(false);
        txt_marca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_marca.setName("txt_marca"); // NOI18N
        txt_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_marcaFocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Status");

        txt_modelo.setForeground(new java.awt.Color(153, 153, 153));
        txt_modelo.setText(" Modelo");
        txt_modelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_modelo.setEnabled(false);
        txt_modelo.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_modelo.setName("txt_modelo"); // NOI18N
        txt_modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_modeloFocusGained(evt);
            }
        });

        txt_ano.setForeground(new java.awt.Color(153, 153, 153));
        txt_ano.setText(" Ano");
        txt_ano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_ano.setEnabled(false);
        txt_ano.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_ano.setName("txt_ano"); // NOI18N
        txt_ano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_anoFocusGained(evt);
            }
        });
        txt_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anoActionPerformed(evt);
            }
        });

        txt_km.setForeground(new java.awt.Color(153, 153, 153));
        txt_km.setText(" Km");
        txt_km.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_km.setEnabled(false);
        txt_km.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_km.setName("txt_km"); // NOI18N
        txt_km.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_kmFocusGained(evt);
            }
        });

        txt_combs.setForeground(new java.awt.Color(153, 153, 153));
        txt_combs.setText(" Tipo de combustível");
        txt_combs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_combs.setEnabled(false);
        txt_combs.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_combs.setName("txt_combs"); // NOI18N
        txt_combs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_combsFocusGained(evt);
            }
        });

        txt_peso.setForeground(new java.awt.Color(153, 153, 153));
        txt_peso.setText(" Peso");
        txt_peso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_peso.setEnabled(false);
        txt_peso.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_peso.setName("txt_peso"); // NOI18N
        txt_peso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pesoFocusGained(evt);
            }
        });
        txt_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesoActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concessionaria64.png"))); // NOI18N

        btn_cadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setName("btn_cadastrar"); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 102, 102));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_cancelar.setName("btn_cancelar"); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(0, 102, 102));
        btn_alterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_alterar.setForeground(new java.awt.Color(255, 255, 255));
        btn_alterar.setText("Alterar");
        btn_alterar.setName("btn_cadastrar"); // NOI18N
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(0, 102, 102));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir");
        btn_excluir.setName("btn_cadastrar"); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        txt_status.setEditable(false);
        txt_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_status.setText(" A venda");
        txt_status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_status.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_status.setName("txt_combs"); // NOI18N

        btn_salvar.setBackground(new java.awt.Color(0, 102, 102));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Confirmar");
        btn_salvar.setEnabled(false);
        btn_salvar.setName("btn_salvar"); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        txt_busca.setForeground(new java.awt.Color(153, 153, 153));
        txt_busca.setText(" Buscar pelo número do chassi");
        txt_busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txt_busca.setEnabled(false);
        txt_busca.setMaximumSize(new java.awt.Dimension(17, 17));
        txt_busca.setName("txt_busca"); // NOI18N
        txt_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscaFocusGained(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-de-lupa.png"))); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        btn_buscar.setEnabled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51)
                                .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_chassi, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(txt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_combs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_cilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(txt_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_combs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void txt_cilindradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cilindradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cilindradasActionPerformed

    private void txt_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anoActionPerformed

    private void txt_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        txt_status.setText("A venda");
        txt_chassi.setEnabled(true);
        txt_marca.setEnabled(true);
        txt_modelo.setEnabled(true);
        txt_ano.setEnabled(true);
        txt_km.setEnabled(true);
        txt_combs.setEnabled(true);
        txt_peso.setEnabled(true);
        txt_cilindradas.setEnabled(true);
        txt_chassi.setEnabled(true);
        cmb_tipo.setEnabled(true);
        
        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_chassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chassiActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       JFormCadastroMoto.this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       //Verificar se achou o número, se achou fazer tudo aqui embaixo
        String chassi;
        boolean flag = false;
       
        txt_chassi.setText("");
        txt_marca.setText("");
        txt_modelo.setText("");
        txt_ano.setText("");
        txt_km.setText("");
        txt_combs.setText("");
        txt_peso.setText("");
        txt_cilindradas.setText("");
        txt_chassi.setText("");
        txt_status.setText("");
        
        btn_salvar.setEnabled(true);
        txt_busca.setEnabled(false);
        btn_buscar.setEnabled(false);
        
        chassi = txt_busca.getText();
        if(chassi.isEmpty() || chassi.equals("Buscar pelo número do chassi"))
        {
            JOptionPane.showMessageDialog(null, "Insira o número do chassi!", "Erro", JOptionPane.ERROR_MESSAGE);
            JFormCadastroMoto.this.setVisible(false);
        }
        else
        {
            try
            {
                FileReader arq = new FileReader(".//src//Model//motocicletas.txt");
                BufferedReader lerArq = new BufferedReader(arq);
                while(lerArq.ready() && flag == false)
                {
                    String linha = lerArq.readLine();
                    String[] dadoSeparado = linha.split(";");
                    if(dadoSeparado[0].equals(chassi))
                    {
                        flag = true;
                        
                        txt_chassi.setText(chassi);
                        txt_marca.setText(dadoSeparado[1]);
                        txt_modelo.setText(dadoSeparado[2]);
                        txt_ano.setText(dadoSeparado[3]);
                        txt_km.setText(dadoSeparado[4]);
                        txt_combs.setText(dadoSeparado[5]);
                        txt_peso.setText(dadoSeparado[6]);
                        txt_status.setText(dadoSeparado[7]);
                        txt_cilindradas.setText(dadoSeparado[8]);
                        cmb_tipo.setSelectedItem(dadoSeparado[9]);
                    }
                }

                lerArq.close();
                if(flag == false)
                     JOptionPane.showMessageDialog(null, "Número do chassi não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                     
            }

            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados no arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
                
            }

        }
        
        if(this.btn_alterar.isEnabled())
        {
            txt_chassi.setEnabled(false);
            txt_marca.setEnabled(true);
            txt_modelo.setEnabled(true);
            txt_ano.setEnabled(true);
            txt_km.setEnabled(true);
            txt_combs.setEnabled(true);
            txt_peso.setEnabled(true);
            txt_cilindradas.setEnabled(true);
            txt_chassi.setEnabled(true);
            cmb_tipo.setEnabled(true);
        }
        
        else if(this.btn_excluir.isEnabled())
        {
            txt_chassi.setEnabled(false);
            txt_marca.setEnabled(false);
            txt_modelo.setEnabled(false);
            txt_ano.setEnabled(false);
            txt_km.setEnabled(false);
            txt_combs.setEnabled(false);
            txt_peso.setEnabled(false);
            txt_cilindradas.setEnabled(false);
            txt_chassi.setEnabled(false);
            cmb_tipo.setEnabled(false);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        txt_busca.setText("");
        txt_busca.setEnabled(true);
        btn_buscar.setEnabled(true);
        btn_cadastrar.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_salvar.setEnabled(false);
        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        if((this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false) || (btn_cadastrar.isEnabled() == false && btn_excluir.isEnabled() == false))
        {
           String chassi, marca, modelo, tipo, status, tipoCombustivel;
           int ano;
           double peso, km, cilindradas;
            
           //Pega os dados
           chassi = txt_chassi.getText();
           marca = txt_marca.getText();
           modelo = txt_modelo.getText();
           tipo = cmb_tipo.getSelectedItem().toString();
           status = txt_status.getText();
           tipoCombustivel = txt_combs.getText();
           ano = Integer.parseInt(txt_ano.getText());
           km = Double.parseDouble(txt_km.getText());
           peso = Double.parseDouble(txt_peso.getText());
           cilindradas = Double.parseDouble(txt_cilindradas.getText());
           
           //Confere
           if(chassi.isEmpty() || chassi.equals("Número do Chassi"))
               JOptionPane.showMessageDialog(null, "Campo chassi não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(marca.isEmpty() || marca.equals("Marca"))
               JOptionPane.showMessageDialog(null, "Campo marca não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(modelo.isEmpty() || modelo.equals("Modelo"))
               JOptionPane.showMessageDialog(null, "Campo modelo não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(tipoCombustivel.isEmpty() || tipoCombustivel.equals("Tipo de combustível"))
               JOptionPane.showMessageDialog(null, "Campo combustível não preenchido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(ano < 1950 || ano > 2050)
               JOptionPane.showMessageDialog(null, "Ano inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(km < 0)
               JOptionPane.showMessageDialog(null, "Km inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(peso < 0 || peso > 10000)
               JOptionPane.showMessageDialog(null, "Peso inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else if(cilindradas < 1)
               JOptionPane.showMessageDialog(null, "Cilindradas inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
           else
           {
               //Cria objeto
               Motocicleta motocicleta = new Motocicleta(cilindradas, tipo, chassi, marca, modelo, ano, km, tipoCombustivel, peso, status);
               if(this.btn_alterar.isEnabled() == false && this.btn_excluir.isEnabled() == false)
               {
                   motocicleta.cadastrar(); //Cadastrar
                   JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                   //JFormCadastroMoto.this.setVisible(false);
               }
                    
               
               else //Alterar
               {
                   motocicleta.alterar();
                   JOptionPane.showMessageDialog(null, "Veículo alterado com sucesso!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                   //JFormCadastroMoto.this.setVisible(false);
               }
           }
        }
        
        else if(btn_cadastrar.isEnabled() == false && btn_alterar.isEnabled() == false) //Excluir
        {
            Motocicleta motocicleta = new Motocicleta(txt_chassi.getText());
            motocicleta.excluir();
            JOptionPane.showMessageDialog(null, "Veículo excluído com sucesso!", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
            //JFormCadastroMoto.this.setVisible(false);
        }
        
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_salvar.setEnabled(false);
        
       //Limpa os campos
       Font fonte = new Font("Tahoma", Font.PLAIN, 11);
       
       txt_chassi.setFont(fonte);
       txt_chassi.setForeground(Color.LIGHT_GRAY);
       txt_marca.setFont(fonte);
       txt_marca.setForeground(Color.LIGHT_GRAY);
       txt_modelo.setFont(fonte);
       txt_modelo.setForeground(Color.LIGHT_GRAY);
       txt_ano.setFont(fonte);
       txt_ano.setForeground(Color.LIGHT_GRAY);
       txt_km.setFont(fonte);
       txt_km.setForeground(Color.LIGHT_GRAY);
       txt_combs.setFont(fonte);
       txt_combs.setForeground(Color.LIGHT_GRAY);
       txt_peso.setFont(fonte);
       txt_peso.setForeground(Color.LIGHT_GRAY);
       txt_cilindradas.setFont(fonte);
       txt_cilindradas.setForeground(Color.LIGHT_GRAY);
       txt_busca.setFont(fonte);
       txt_busca.setForeground(Color.LIGHT_GRAY);
       
       txt_chassi.setText("Número do Chassi");
       txt_marca.setText("Marca");
       txt_modelo.setText("Modelo");
       txt_ano.setText("Ano");
       txt_km.setText("Km");
       txt_combs.setText("Tipo de combustível");
       txt_peso.setText("Peso");
       txt_cilindradas.setText("Cilindradas");
       txt_busca.setText("Buscar pelo número do chassi");
       
            txt_chassi.setEnabled(false);
            txt_marca.setEnabled(false);
            txt_modelo.setEnabled(false);
            txt_ano.setEnabled(false);
            txt_km.setEnabled(false);
            txt_combs.setEnabled(false);
            txt_peso.setEnabled(false);
            txt_cilindradas.setEnabled(false);
            txt_chassi.setEnabled(false);
            cmb_tipo.setEnabled(false);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscaFocusGained
        txt_busca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_busca.setFont(fonte);
        txt_busca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_buscaFocusGained

    private void txt_chassiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_chassiFocusGained
        txt_chassi.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_chassi.setFont(fonte);
        txt_chassi.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_chassiFocusGained

    private void txt_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusGained
        txt_marca.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_marca.setFont(fonte);
        txt_marca.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_marcaFocusGained

    private void txt_modeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_modeloFocusGained
        txt_modelo.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_modelo.setFont(fonte);
        txt_modelo.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_modeloFocusGained

    private void txt_anoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_anoFocusGained
        txt_ano.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_ano.setFont(fonte);
        txt_ano.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_anoFocusGained

    private void txt_kmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_kmFocusGained
        txt_km.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_km.setFont(fonte);
        txt_km.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_kmFocusGained

    private void txt_combsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_combsFocusGained
        txt_combs.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_combs.setFont(fonte);
        txt_combs.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_combsFocusGained

    private void txt_pesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pesoFocusGained
        txt_peso.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_peso.setFont(fonte);
        txt_peso.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_pesoFocusGained

    private void txt_cilindradasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cilindradasFocusGained
        txt_cilindradas.setText("");
        Font fonte = new Font("Tahoma", Font.PLAIN, 14);
        txt_cilindradas.setFont(fonte);
        txt_cilindradas.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_cilindradasFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCadastroMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_chassi;
    private javax.swing.JTextField txt_cilindradas;
    private javax.swing.JTextField txt_combs;
    private javax.swing.JTextField txt_km;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
